// Generated by https://quicktype.io

export interface Labels {
    id:          number;
    node_id:     string;
    url:         string;
    name:        string;
    color:       string;
    default:     boolean;
    description: string;
}

